/** @type {import('tailwindcss').Config} */
// Design tokens exported from Stitch project "AutoHired AI Application Tracker"
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#0f0069",
        tertiary: "#571ac0",
        "on-tertiary-fixed": "#23005c",
        "secondary-fixed": "#c9e6ff",
        "outline-variant": "#c7c4d8",
        "on-primary-fixed-variant": "#3323cc",
        "inverse-primary": "#c3c0ff",
        outline: "#777587",
        "on-tertiary-fixed-variant": "#5516be",
        "surface-container-high": "#dee8ff",
        "primary-container": "#4f46e5",
        "primary-fixed": "#e2dfff",
        "surface-container-highest": "#d8e3fb",
        "surface-variant": "#d8e3fb",
        "on-primary": "#ffffff",
        secondary: "#006591",
        "tertiary-fixed": "#e9ddff",
        "on-secondary-fixed": "#001e2f",
        "inverse-on-surface": "#ecf1ff",
        "secondary-container": "#39b8fd",
        "on-surface": "#111c2d",
        "primary-fixed-dim": "#c3c0ff",
        "tertiary-container": "#6f3dd9",
        surface: "#f9f9ff",
        "on-secondary-fixed-variant": "#004c6e",
        "surface-tint": "#4d44e3",
        "on-surface-variant": "#464555",
        "secondary-fixed-dim": "#89ceff",
        "on-secondary": "#ffffff",
        "on-tertiary": "#ffffff",
        "inverse-surface": "#263143",
        error: "#ba1a1a",
        "on-primary-container": "#dad7ff",
        "surface-container-lowest": "#ffffff",
        "on-secondary-container": "#004666",
        "surface-container": "#e7eeff",
        "surface-bright": "#f9f9ff",
        "surface-container-low": "#f0f3ff",
        "on-error-container": "#93000a",
        "on-error": "#ffffff",
        "tertiary-fixed-dim": "#d0bcff",
        primary: "#3525cd",
        "on-background": "#111c2d",
        background: "#f9f9ff",
        "error-container": "#ffdad6",
        "surface-dim": "#cfdaf2",
        "on-tertiary-container": "#e3d5ff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "stack-xl": "64px",
        "stack-sm": "8px",
        gutter: "16px",
        "stack-lg": "32px",
        "container-margin": "20px",
        "stack-md": "16px",
        unit: "4px",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "label-md": [
          "14px",
          { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" },
        ],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg-mobile": [
          "24px",
          { lineHeight: "32px", fontWeight: "700" },
        ],
        "display-lg": [
          "48px",
          { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "800" },
        ],
      },
      boxShadow: {
        "level-1":
          "0 4px 6px -1px rgb(0 0 0 / 0.05), 0 2px 4px -2px rgb(0 0 0 / 0.05)",
        "level-2": "0 10px 15px -3px rgb(0 0 0 / 0.1)",
      },
    },
  },
  plugins: [],
};
